import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getUsers } from '../helpers/users'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
     {props.name}
     {props.users.map(user => (
       <div key={user.id}>{user.name}</div>
      ))}
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const users = getUsers();

  return {
    props: {
      name: 'John Doe',
      users: users
    }, // will be passed to the page component as props
  }
}